-- noinspection SqlDialectInspectionForFile

# --- USER, PROJECT AND PROJECT_LINK schemas

# --- !Ups

CREATE TABLE "USER"
(
    UUID     UUID         NOT NULL PRIMARY KEY,
    LOGIN    VARCHAR(64)  NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL UNIQUE,
    VERIFIED BOOLEAN      NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX EMAIL_IDX on "USER" (EMAIL);

CREATE TABLE "PROJECT"
(
    UUID            UUID         NOT NULL PRIMARY KEY,
    NAME            VARCHAR(255) NOT NULL,
    OWNER_ID        UUID         NOT NULL,
    FOLDER          VARCHAR(510) NOT NULL,
    MAX_FILE_SIZE   BIGINT       NOT NULL,
    MAX_FILES_COUNT BIGINT       NOT NULL,
    FOREIGN KEY (OWNER_ID) REFERENCES "USER" (UUID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX OWNER_INDEX on "PROJECT" (OWNER_ID);

CREATE TABLE "PROJECT_LINK"
(
    UUID                    UUID    NOT NULL PRIMARY KEY,
    PROJECT_ID              UUID    NOT NULL,
    IS_SHARED               BOOLEAN NOT NULL,
    IS_UPLOAD_ALLOWED       BOOLEAN NOT NULL,
    IS_DELETE_ALLOWED       BOOLEAN NOT NULL,
    IS_MODIFICATION_ALLOWED BOOLEAN NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES "PROJECT" (UUID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX PROJECT_ID_IDX on "PROJECT_LINK" (PROJECT_ID);

# --- !Downs

DROP INDEX PROJECT_ID_IDX;
DROP TABLE "PROJECT_LINK";

DROP INDEX OWNER_INDEX;
DROP TABLE "PROJECT";

DROP INDEX EMAIL_IDX;
DROP TABLE "USER";
