-- noinspection SqlResolveForFile

# -- noinspection SqlDialectInspectionForFile

# --- !Ups

CREATE TABLE "VERIFICATION_TOKEN"
(
    ID         BIGSERIAL NOT NULL PRIMARY KEY,
    TOKEN      UUID      NOT NULL UNIQUE,
    USER_ID    UUID      NOT NULL,
    EXPIRED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX VERIFICATION_TOKEN_TABLE_TOKEN_IDX on "VERIFICATION_TOKEN" (TOKEN);

CREATE TABLE "RESET_TOKEN"
(
    ID         BIGSERIAL NOT NULL PRIMARY KEY,
    TOKEN      UUID      NOT NULL UNIQUE,
    USER_ID    UUID      NOT NULL,
    EXPIRED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX RESET_TOKEN_TABLE_TOKEN_IDX on "RESET_TOKEN" (TOKEN);

# --- !Downs

DROP INDEX RESET_TOKEN_TABLE_TOKEN_IDX;
DROP TABLE "RESET_TOKEN";

DROP INDEX VERIFICATION_TOKEN_TABLE_TOKEN_IDX;
DROP TABLE "VERIFICATION_TOKEN";
