-- noinspection SqlResolveForFile

# -- noinspection SqlDialectInspectionForFile

# --- !Ups

CREATE TABLE "VERIFICATION_TOKEN"
(
    TOKEN      UUID      NOT NULL PRIMARY KEY,
    USER_ID    UUID      NOT NULL,
    EXPIRED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "RESET_TOKEN"
(
    TOKEN      UUID      NOT NULL PRIMARY KEY,
    USER_ID    UUID      NOT NULL,
    EXPIRED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES "USER" (UUID) ON UPDATE CASCADE ON DELETE CASCADE
);

# --- !Downs

DROP TABLE "RESET_TOKEN";

DROP TABLE "VERIFICATION_TOKEN";
