version: '3.5'
services:
  database:
    build: ./database
    environment:
      - POSTGRES_DB=vdjsight-docker
      - POSTGRES_USER=vdjsight-docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./backups:/pg_backups
    networks:
      database-backend:
    restart: always

  frontend:
    image: bvdmitri/vdjsight-frontend:${COMPOSE_FRONTEND_IMAGE_TAG}
    networks:
      proxy-network:
    restart: always

  backend:
    image: bvdmitri/vdjsight-backend:${COMPOSE_BACKEND_IMAGE_TAG}
    volumes:
      - ./backend/environment:/home/vdjsight/environment:ro
      - ./backend/logs:/home/vdjsight/logs
    networks:
      database-backend:
      proxy-network:
    links:
      - database:dbserver
    restart: always
    depends_on:
      - database

  proxy:
    image: nginx:alpine
    volumes:
      - ./conf.nginx:/etc/nginx/conf.d/default.conf:ro
    networks:
      proxy-network:
    links:
      - backend:backend
      - frontend:frontend
    ports:
      - 8080:80
    restart: always


networks:
  database-backend:
  proxy-network:





