version: 2.1

executors:
  frontend-executor:
    docker:
      - image: circleci/node:11-browsers

  backend-executor:
    docker:
      - image: bvdmitri/scala-sbt-docker:latest


commands:

  docker-publish:
    description: "A command to publish docker image to public registry"
    parameters:
      project:
        type: string
        default: "nothing"
      tag:
        type: string
        default: "develop"
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push bvdmitri/<< parameters.project >>:<< parameters.tag >>

jobs:
  frontend:
    executor: frontend-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-cache-1-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install frontend dependencies
          command: ./vdjsight.sh frontend install
      - save_cache:
          key: frontend-cache-1-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run:
          name: Testing frontend
          command: ./vdjsight.sh frontend test-ci
      - run:
          name: Building frontend
          command: ./vdjsight.sh frontend build
      - persist_to_workspace:
          root: ~/project/frontend
          paths:
            - dist

  frontend-publish:
    executor: frontend-executor
    parameters:
      tag:
        type: string
        default: "develop"
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project/frontend
      - run:
          name: Build frontend docker
          command: ./vdjsight.sh frontend docker << parameters.tag >> --fast
      - docker-publish:
          project: "vdjsight-frontend"
          tag: << parameters.tag >>

  backend:
    executor: backend-executor
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile dist package
          command: ./vdjsight.sh backend build
      - run:
          name: Test package
          command: ./vdjsight.sh backend test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - persist_to_workspace:
          root: ~/project/backend
          paths:
            - target

  backend-publish:
    executor: backend-executor
    parameters:
      tag:
        type: string
        default: "develop"
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/project/backend
      - restore_cache:
          key: sbt-cache
      - run:
          name: Build backend docker
          command: ./vdjsight.sh backend docker << parameters.tag >>
      - docker-publish:
          project: "vdjsight-backend"
          tag: << parameters.tag >>


workflows:
  version: 2
  main:
    jobs:
      - frontend:
          filters:
            branches:
              only:
                - master
                - develop

      - frontend-publish:
          tag: develop
          context: docker-hub-registry
          requires:
            - frontend
          filters:
            branches:
              only:
                - develop

      - frontend-publish:
          tag: latest
          context: docker-hub-registry
          requires:
            - frontend
          filters:
            branches:
              only:
                - master

      - backend:
          filters:
            branches:
              only:
                - master
                - develop

      - backend-publish:
          tag: develop
          context: docker-hub-registry
          requires:
            - backend
          filters:
            branches:
              only:
                - develop

      - backend-publish:
          tag: latest
          context: docker-hub-registry
          requires:
            - backend
          filters:
            branches:
              only:
                - master


