version: 2.1

executors:
  frontend-docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
  backend-docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch


commands:

  docker-publish:
    description: "A command to publish docker image to public registry"
    parameters:
      project:
        type: string
        default: "nothing"
      tag:
        type: string
        default: "develop"
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push bvdmitri/<< parameters.project >>:<< parameters.tag >>

jobs:
  frontend:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-libs-1-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Install frontend dependencies
          command: ./vdjsight.sh frontend install
      - save_cache:
          key: frontend-libs-1-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run:
          name: Testing frontend
          command: ./vdjsight.sh frontend test-ci
      - run:
          name: Building frontend
          command: ./vdjsight.sh frontend build

  frontend-publish:
    executor: frontend-docker-publisher
    parameters:
      tag:
        type: string
        default: "develop"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - frontend-libs-1-{{ checksum "frontend/yarn.lock" }}
      - run:
          name: Build frontend docker
          command: ./vdjsight.sh frontend docker << parameters.tag >>
      - docker-publish:
          project: "vdjsight-frontend"
          tag: << parameters.tag >>

  backend:
    docker:
      - image: openjdk:11
    environment:
      SBT_VERSION: 1.2.8
    steps:
      - run:
          name: Get SBT binaries
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt python-pip git
            pip install awscli
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile dist package
          command: ./vdjsight.sh backend build
      - run:
          name: Test package
          command: ./vdjsight.sh backend test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  main:
    jobs:
      - frontend:
          filters:
            branches:
              only:
                - master
                - develop

      - frontend-publish:
          tag: develop
          context: docker-hub-registry
          requires:
            - frontend
          filters:
            branches:
              only:
                - develop

      - frontend-publish:
          tag: latest
          context: docker-hub-registry
          requires:
            - frontend
          filters:
            branches:
              only:
                - master

      - backend:
          filters:
            branches:
              only:
                - master
                - develop

