version: 2.1

executors:
  frontend-executor:
    docker:
      - image: circleci/node:11-browsers

  backend-executor:
    docker:
      - image: bvdmitri/scala-sbt-docker:latest


commands:

  docker-publish:
    description: "A command to publish docker image to public registry"
    parameters:
      project:
        type: string
        default: "nothing"
      tag:
        type: string
        default: "develop"
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            if [[ -f ".docker-created" ]]; then
              echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
              docker push << parameters.project >>:${CIRCLE_BRANCH}
            else
              echo "Skipping publishing because there is no .docker-created file"
            fi

jobs:
  frontend:
    executor: frontend-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-cache-4-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
            - frontend-cache-4-{{ .Branch }}
            - frontend-cache-4
      - run:
          name: Install frontend dependencies
          command: ./vdjsight.sh frontend install
      - run:
          name: Building frontend
          command: ./vdjsight.sh frontend build
      - run:
          name: Testing frontend
          command: ./vdjsight.sh frontend test --ci
      - setup_remote_docker
      - run:
          name: Creating frontend docker image
          command: |
            ./vdjsight.sh frontend docker ${CIRCLE_BRANCH} --fast
            touch .docker-created
      - docker-publish:
          project: bvdmitri/vdjsight-frontend
      - run:
          name: Delete semantic-ui
          working_directory: ~/project/frontend
          command: |
            rm -rf node_modules/semantic-ui || true
            rm -rf node_modules/fomantic-ui || true
      - save_cache:
          key: frontend-cache-4-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules

  backend:
    executor: backend-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-cache-4-{{ .Branch }}-{{ checksum "backend/build.sbt" }}
            - backend-cache-4-{{ .Branch }}
            - backend-cache-4
      - run:
          name: Building dependencies
          command: ./vdjsight.sh dependencies install mir
      - run:
          name: Building backend
          command: ./vdjsight.sh backend build
      - run:
          name: Testing backend
          command: ./vdjsight.sh backend test
      - setup_remote_docker
      - run:
          name: Creating backend docker image
          command: |
            ./vdjsight.sh backend docker ${CIRCLE_BRANCH}
            touch .docker-created
      - docker-publish:
          project: bvdmitri/vdjsight-backend
      - save_cache:
          key: backend-cache-4-{{ .Branch }}-{{ checksum "backend/build.sbt" }}
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
            - "~/project/backend/target"


workflows:
  version: 2
  main:
    jobs:
      - frontend:
          context: docker-hub-registry
          filters:
            branches:
              only:
                - master
                - develop

      - backend:
          context: docker-hub-registry
          filters:
            branches:
              only:
                - master
                - develop

