version: 2.1
jobs:
  frontend:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - frontend-libs-1-{{ checksum "frontend/yarn.lock" }}\
      - run:
          name: Install frontend dependencies
          command: ./vdjsight.sh frontend install
      - save_cache:
          key: frontend-libs-1-{{ checksum "frontend/yarn.lock" }}
          paths:
            - frontend/node_modules
      - run:
          name: Testing frontend
          command: ./vdjsight.sh frontend test-ci
      - run:
          name: Building frontend
          command: ./vdjsight.sh frontend build

  backend:
    docker:
      - image: openjdk:11
    environment:
      SBT_VERSION: 1.2.8
    steps:
      - run:
          name: Get SBT binaries
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
            apt-get update
            apt-get install -y sbt python-pip git
            pip install awscli
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile dist package
          command: ./vdjsight.sh backend build
      - run:
          name: Test package
          command: ./vdjsight.sh backend test
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

workflows:
  version: 2
  main:
    jobs:
      - frontend:
          filters:
            branches:
              only:
                - master
                - develop

      - backend:
          filters:
            branches:
              only:
                - master
                - develop

