version: '3.5'
services:
  db:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=vdjsight-dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - "8001:8080"
